create table if not exists public.cakes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  description text not null default '' check (char_length(description) <= 500),
  media_url text not null,
  media_path text,
  media_type text not null check (media_type in ('image', 'video')),
  created_at timestamptz not null default now()
);

alter table public.cakes add column if not exists media_path text;
update public.cakes
set media_path = 'legacy/' || id::text
where media_path is null;
alter table public.cakes alter column media_path set not null;
create unique index if not exists cakes_media_path_unique_idx
  on public.cakes (media_path);

alter table public.cakes enable row level security;
grant select on public.cakes to anon, authenticated;
grant insert on public.cakes to authenticated;
grant usage, select on sequence public.cakes_id_seq to authenticated;

drop policy if exists "Anyone can view cakes" on public.cakes;
create policy "Anyone can view cakes"
  on public.cakes for select
  to anon, authenticated
  using (true);

drop policy if exists "Signed-in admins can add cakes" on public.cakes;
create policy "Signed-in admins can add cakes"
  on public.cakes for insert
  to authenticated
  with check (true);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'cakes',
  'cakes',
  true,
  52428800,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Anyone can view cake media" on storage.objects;
create policy "Anyone can view cake media"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'cakes');

drop policy if exists "Signed-in admins can upload cake media" on storage.objects;
create policy "Signed-in admins can upload cake media"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'cakes');

drop policy if exists "Signed-in admins can remove cake media" on storage.objects;
create policy "Signed-in admins can remove cake media"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'cakes');
